language: node_js

## Git configuration
git:
  depth: 5  # limit clone depth
  submodules: false

## Enable caching
cache:
  yarn: true
  directories:
    - node_modules


## Custom job 'definitions'
definitions:
  local-test: &local-test
    stage: local-test
    install: yarn
    script:
      - echo "Running local test against $(node -v)..."
      - yarn test

  global-test: &global-test
    stage: global-test
    install: yarn global add "https://github.com/$TRAVIS_REPO_SLUG#$TRAVIS_BRANCH"
    script:
      - echo "Running global test against $(node -v)..."
      - yarn test-global
    # Attempt to skip Git cloning (doesn't work as of 02-06-18)
    # branches
    #   - only: "" 

## Build stages
jobs:
  include:
    ## Local tests (with differing Node versions)
    - <<: *local-test
      node_js: "node"
    - <<: *local-test
      node_js: "stable"
    - <<: *local-test
      node_js: "9.*"  # version lts/* (8.11.2) doesn't seem to work

    ## Global tests (with differing Node versions)
    - <<: *global-test
      node_js: "node"
    - <<: *global-test
      node_js: "stable"
    - <<: *global-test 
      node_js: "9.*"  # version lts/* (8.11.2) doesn't seem to work
