language: node_js

cache:
  yarn: true
  directories:
    - node_modules

# Custom job 'definitions'
definitions:
  local-test: &local-test
    stage: local-test
    install: yarn
    script:
      - echo "Running local test against $(node -v)..."
      - yarn test

  global-test: &global-test
    stage: global-test
    install: yarn global add "https://github.com/$TRAVIS_REPO_SLUG#$TRAVIS_BRANCH"
    script:
      - echo "Running global test against $(node -v)..."
      - yarn test-global

jobs:
  include:
    # Local tests
    - <<: *local-test
      node_js: "node"
    - <<: *local-test
      node_js: "stable"

    # Global tests
    - <<: *global-test
      node_js: "node"
    - <<: *global-test
      node_js: "stable"
